"""Add market data table

Revision ID: f40c9c792f49
Revises: 472e6e2810f4
Create Date: 2026-10-02 11:48:23.465999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40c9c792f49'
down_revision: Union[str, Sequence[str], None] = '472e6e2810f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Double(), nullable=False),
    sa.Column('high', sa.Double(), nullable=False),
    sa.Column('low', sa.Double(), nullable=False),
    sa.Column('close', sa.Double(), nullable=False),
    sa.Column('tick_volume', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('spread', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_data')
    # ### end Alembic commands ###
